version: '3.8'

services:
  web:
    build: .
    container_name: django_sqlite_app
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
